"""run — the ONE-command orchestrator + CLI (S6 synthetic; M1 S4 real-image).

Wires the whole pipeline behind one command. Two entry paths share the SAME blind solve -> detect ->
measure(recovered WCS) -> score core:

    synthetic (default):  build_scene -> render_scene -> ...
    real (--image/--meta): ingest_external_image -> assemble_real_truth -> ...

In both, the answer is produced by a sole WRITER (render / realtruth), the solver receives a WCS-free
image + a coarse scale hint only (BLIND), the measurement uses the BLIND-recovered WCS (never a header
WCS), and ``score`` is the SOLE reader of the sealed answer (run hands it the answer PATH).

HONEST FAILURE is the load-bearing contract. A typed ``SolveFailure`` / ``DetectFailure`` surfaces as
a labelled message + a NON-ZERO exit code + NO residual.txt — never a stack trace and never a
fabricated residual. On the REAL path an additional honest failure exists: a blind solve that locks
onto the WRONG field (AC 4.6) — its recovered field does not overlap the expected pointing field — is
reported as a typed failure, NOT a flattering residual.

The seal: run never reads the sealed answer itself. It hands ``score`` the answer PATH (score is the
sole reader) and uses the BLIND-recovered WCS — never the true WCS — for the measurement. (Pinned by
tests/test_run.py + tests/test_run_image.py.)
"""
from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

# Module-level imports so tests can monkeypatch tracklet.run.{solve_pointing,detect_streak,...}.
from tracklet.detect_streak import DetectFailure, detect_streak
from tracklet.ingest import ingest_external_image
from tracklet.measure_position import measure_position
from tracklet.realgate import check_field_overlap, wcs_center_radec
from tracklet.realtruth import assemble_real_truth
from tracklet.render import render_scene
from tracklet.report import OverlayInputs, write_report
from tracklet.scene import (
    build_scene,
    default_catalogue_path,
    default_tle_path,
    load_catalogue,
    load_tle,
)
from tracklet.score import score
from tracklet.solve_pointing import SolveFailure, solve_pointing

_REPO = Path(__file__).resolve().parent.parent.parent
_DEFAULT_CONFIG = _REPO / "config" / "default_scene.toml"
_DEFAULT_OUT = _REPO / "out"


def _parse_args(argv: "list[str] | None") -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="tracklet.run",
        description="Run the tracklet optical-SDA pipeline end to end on the synthetic scene.",
    )
    parser.add_argument(
        "--config", default=str(_DEFAULT_CONFIG), help="path to the scene TOML (default: %(default)s)"
    )
    parser.add_argument(
        "--out", default=str(_DEFAULT_OUT), help="output directory (default: %(default)s)"
    )
    parser.add_argument(
        "--image", default=None,
        help="real-frame mode: path to a genuine telescope FITS frame (requires --meta)",
    )
    parser.add_argument(
        "--meta", default=None,
        help="real-frame mode: path to the frame's meta.toml (timing/site/pointing/satellite)",
    )
    args = parser.parse_args(argv)
    if (args.image is None) != (args.meta is None):
        parser.error("--image and --meta must be given together (real-frame mode needs both)")
    return args


def main(argv: "list[str] | None" = None) -> int:
    """Run the whole pipeline once; return 0 on success, non-zero on an HONEST solve/detect failure."""
    from tracklet._env import assert_supported_python

    assert_supported_python()  # runtime guard: wrong Python minor fails loud before anything else

    args = _parse_args(argv)
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Clear any RESULT artifacts from a prior run FIRST, so a later FAILED run can never leave a
    # stale residual/report/overlay on disk that a stranger could mistake for the current result.
    # These are (re)written only on a real computed residual; the rendered image + the sealed answer
    # are regenerated by render_scene below.
    for _stale in ("residual.txt", "report.md", "overlay.png"):
        (out_dir / _stale).unlink(missing_ok=True)

    if args.image is not None:
        return _run_real(args, out_dir)
    return _run_synthetic(args, out_dir)


def _run_synthetic(args, out_dir: Path) -> int:
    """The M0 synthetic path: render a scene from frozen fixtures, then the shared solve/score core."""
    # 1) Scene + frozen real-data fixtures (offline; no network).
    scene = build_scene(args.config)
    catalogue = load_catalogue(default_catalogue_path(scene))
    tle = load_tle(default_tle_path(scene))

    # 2) Render -> the CLEAN (WCS-free) image.fits + the SEALED answer (render is the sole writer).
    rr = render_scene(scene, catalogue, tle, out_dir)

    # 3) BLIND plate-solve. A SolveFailure is HONEST: labelled message, no residual, non-zero exit.
    solve = solve_pointing(str(rr.image_path), {"fov_deg": scene.fov_deg})
    if isinstance(solve, SolveFailure):
        print(f"could not solve: {solve.reason}")
        return 2

    # 4) Detect the streak. A DetectFailure is equally HONEST.
    detection = detect_streak(str(rr.image_path))
    if isinstance(detection, DetectFailure):
        print(f"could not detect: {detection.reason}")
        return 3

    # 5) Measure through the BLIND-RECOVERED WCS (never the true WCS), then 6) score against the
    #    sealed answer PATH (score is the sole reader — run never opens the answer itself).
    measured = measure_position(detection, solve.wcs)
    result = score(measured, str(rr.truth_path))

    # 7) Write the FINITE residual (only ever written on a real, computed residual).
    (out_dir / "residual.txt").write_text(f"{result.residual_arcsec:.6f}\n")

    # 8) Surface the headline number + verdict, and write the human report.
    verdict = "PASS" if result.passed else "FAIL"
    print(
        f"residual: {result.residual_arcsec:.4f}\" "
        f"(threshold {result.threshold_arcsec}\") -> {verdict}"
    )
    overlay_inputs = OverlayInputs(
        image_path=rr.image_path, detection=detection, recovered_wcs=solve.wcs, scene=scene
    )
    write_report(result, overlay_inputs, str(out_dir))
    return 0


def _run_real(args, out_dir: Path) -> int:
    """The M1 real-frame path: ingest a genuine FITS, assemble sealed satellite-truth, then the shared
    BLIND solve -> detect -> AC-4.6 plausibility gate -> measure -> score core.

    The blind solve receives only the WCS-free ingested image + a coarse scale hint (no position
    prior). A wrong-field lock (recovered field does not overlap the expected pointing field) is an
    HONEST typed failure, not a flattering residual (AC 4.6). The header WCS, when present, is read
    only by the report diagnostic in-memory — never fed into the solver.
    """
    with open(args.meta, "rb") as fh:
        meta = tomllib.load(fh)

    # 1) Ingest the real frame -> normalized, WCS-stripped clean image (the solver-facing artifact).
    ingest = ingest_external_image(args.image, meta, str(out_dir))

    # 2) Assemble the SEALED satellite-truth (realtruth is the sole writer; the header WCS is carried
    #    in-memory for the report diagnostic only). The committed TLE drives the propagation.
    tle = load_tle(meta["satellite"]["tle_file"] if Path(meta["satellite"]["tle_file"]).is_absolute()
                   else str(Path(args.meta).resolve().parent / meta["satellite"]["tle_file"]))
    rt = assemble_real_truth(tle, meta, str(out_dir), pointing_wcs=None)

    # 3) BLIND plate-solve the CLEAN image (WCS-free image + coarse scale hint ONLY — no position
    #    prior, no header WCS). A SolveFailure is HONEST.
    fov_deg = float(meta["solver"]["fov_deg"])
    solve = solve_pointing(str(ingest.image_path), {"fov_deg": fov_deg})
    if isinstance(solve, SolveFailure):
        print(f"could not solve: {solve.reason}")
        return 2

    # 4) Detect the trail. A DetectFailure is equally HONEST.
    detection = detect_streak(str(ingest.image_path))
    if isinstance(detection, DetectFailure):
        print(f"could not detect: {detection.reason}")
        return 3

    # 5) AC 4.6 PLAUSIBILITY GATE (anti wrong-field-lock), computed downstream of the solver from
    #    in-memory WCS centers — NEVER fed back in. The expected pointing center is the commanded
    #    mount pointing plus the FIXED camera offset (provided in meta, derived NON-CIRCULARLY from
    #    OTHER frames of this camera). If the offset is absent, fall back to the commanded center.
    naxis2, naxis1 = ingest.image.shape
    rec_ra, rec_dec = wcs_center_radec(solve.wcs, naxis1, naxis2)
    expected = _expected_pointing_center(meta)
    plausible = check_field_overlap((rec_ra, rec_dec), expected, fov_deg)
    if not plausible.ok:
        print(
            "could not trust solve: wrong field lock — recovered field "
            f"({rec_ra:.4f}, {rec_dec:.4f}) does not overlap expected "
            f"({expected[0]:.4f}, {expected[1]:.4f}); separation "
            f"{plausible.separation_deg:.4f} deg > tolerance {plausible.tolerance_deg:.4f} deg "
            "(0.5 x fov). No residual reported (honest typed failure, AC 4.6)."
        )
        return 4

    # 6) Measure through the BLIND-RECOVERED WCS (never the header WCS), then 7) score against the
    #    sealed answer PATH (score is the sole reader — run never opens the answer itself).
    measured = measure_position(detection, solve.wcs)
    result = score(measured, str(rt.truth_path))

    # 8) Write the FINITE residual (only ever written on a real, plausibility-passing residual).
    (out_dir / "residual.txt").write_text(f"{result.residual_arcsec:.6f}\n")

    verdict = "PASS" if result.passed else "FAIL"
    print(
        f"residual: {result.residual_arcsec:.4f}\" "
        f"(threshold {result.threshold_arcsec}\") -> {verdict}"
    )
    _write_real_report(
        out_dir, result, meta, rec_ra, rec_dec, expected, plausible, detection, tle, rt
    )
    return 0


def _tle_age_days(tle, exposure_mid_utc) -> float:
    """Age of the TLE epoch relative to the exposure midpoint, in days (>= 0 when the epoch precedes
    the exposure). Decodes the standard TLE epoch field (line 1, cols 19-32: ``YYDDD.DDDDDDDD``) into a
    UTC datetime and subtracts — metadata extraction, not a propagation (skyfield does the propagation).
    Returns 0.0 if the midpoint is unavailable (e.g. a stubbed truth in a non-frame test)."""
    import datetime as _dt

    if exposure_mid_utc is None:
        return 0.0
    field = tle.line1[18:32]
    yy = int(field[0:2])
    doy = float(field[2:])
    year = 2000 + yy if yy < 57 else 1900 + yy  # standard TLE 2-digit-year pivot
    epoch = _dt.datetime(year, 1, 1, tzinfo=_dt.timezone.utc) + _dt.timedelta(days=doy - 1.0)
    return (exposure_mid_utc - epoch).total_seconds() / 86400.0


def _expected_pointing_center(meta: dict) -> "tuple[float, float]":
    """The independently-known pointing center for the AC-4.6 gate: commanded mount pointing
    (STRCURA/STRCUDE) plus a FIXED camera offset (``meta['pointing']['camera_offset_ra_deg']`` /
    ``camera_offset_dec_deg``) when present — derived NON-CIRCULARLY from OTHER frames of this camera,
    never from this frame's own recovered-minus-commanded. Absent an offset, the commanded center is
    used (a conservative gate — it can only reject, never flatter)."""
    p = meta["pointing"]
    ra = float(p["commanded_ra_deg"]) + float(p.get("camera_offset_ra_deg", 0.0))
    dec = float(p["commanded_dec_deg"]) + float(p.get("camera_offset_dec_deg", 0.0))
    return ra, dec


def _write_real_report(
    out_dir, result, meta, rec_ra, rec_dec, expected, plausible, detection, tle, rt
) -> None:
    """The honest M1 real-frame report (Sprint 5): the headline residual + the AC-4.6 plausibility-gate
    result + the FIVE-source degradation report with the TLE-age along-track term flagged DOMINANT + a
    pointing-vs-timing decomposition computed from the IN-MEMORY measured/truth SkyCoords (score stays
    the sole truth deserializer). The degradation section is rendered by ``report.render_degradation_report``;
    here we add the plausibility-gate provenance the gate produced this run."""
    from tracklet.report import DegradationInputs, render_degradation_report

    sat = meta.get("satellite", {})
    obs = meta.get("observatory", {})

    degradation_md = render_degradation_report(
        DegradationInputs(
            score=result,
            detection=detection,
            tle_age_days=_tle_age_days(tle, rt.exposure_mid_utc),
            exposure_s=float(meta["timing"]["exptime_s"]),
            norad_id=sat.get("norad_id"),
            satellite_name=sat.get("name", "?"),
            # The header WCS (pointing-truth) is carried in-memory on the truth result when present;
            # None for DDOTI. Passed in-memory — NEVER deserialized here, NEVER fed into the blind solve.
            pointing_truth=rt.pointing_wcs,
        )
    )

    gate_md = "\n".join(
        [
            "",
            "## Plausibility gate (AC 4.6 — anti wrong-field-lock)",
            f"- Recovered field center: RA {rec_ra:.4f}, Dec {rec_dec:.4f} deg",
            f"- Expected pointing center: RA {expected[0]:.4f}, Dec {expected[1]:.4f} deg "
            "(commanded mount pointing + non-circular C1 camera offset)",
            f"- Separation {plausible.separation_deg:.4f} deg <= tolerance "
            f"{plausible.tolerance_deg:.4f} deg (0.5 x fov) -> field overlap CONFIRMED",
            "",
            "## Provenance",
            f"- Observatory: {obs.get('name', '?')}",
            f"- Plate solver: astrometry.net solve-field (blind — no position seed)",
            "",
            "## What this proves",
            "- A GENUINE telescope frame was blind plate-solved (no position prior) and its real "
            "satellite trail measured to the residual above against independently sealed "
            "TLE-propagated truth — an honest, plausibility-gated, non-circular real-image result.",
            "",
        ]
    )
    (Path(out_dir) / "report.md").write_text(degradation_md + gate_md)


if __name__ == "__main__":
    raise SystemExit(main())
